# https://travis-ci.org/kocsob/syncipy
dist: xenial

# Use containers instead of full VMs for faster startup.
sudo: false

matrix:
    fast_finish: true

language: python

python:
    - 3.5
    - 3.6
    - nightly

install:
    # Install Syncipy as a Python package
    - pip install -e '.[dev]'
    - if [[ $TRAVIS_PYTHON_VERSION != nightly ]]; then pip install codecov; fi

script:
    # Checking lint
    - python -m flake8

    # Run tests
    - python -m pytest --cov

after_success:
    # call codecov from project root
    - if [[ $TRAVIS_PYTHON_VERSION != nightly ]]; then codecov; fi
